(deftheme pleroma
  "Created 2021-06-26.")

(custom-theme-set-faces
 'pleroma
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#050608" :foreground "#e4e4ef" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 150 :width normal :foundry "xos4" :family "Terminus"))))
 '(cursor ((t (:background "#C0A269"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#96a6c8"))))
 '(highlight ((t (:background "#050608"))))
 '(region ((t (:extend t :background "#484848"))))
 '(shadow ((t (:foreground "#52494e"))))
 '(secondary-selection ((t (:extend t :background "#484848"))))
 '(trailing-whitespace ((t (:foreground "#000000" :background "#f43841"))))
 '(font-lock-builtin-face ((t (:foreground "#ffdd33"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#583A67"))))
 '(font-lock-comment-face ((t (:foreground "#283A67"))))
 '(font-lock-constant-face ((t (:foreground "#9ea7a6"))))
 '(font-lock-doc-face ((t (:foreground "#2a495d"))))
 '(font-lock-function-name-face ((t (:foreground "#FFA269"))))
 '(font-lock-keyword-face ((t (:foreground "#d8a070" :weight bold))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#95a99f"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#0fa00f"))))
 '(font-lock-type-face ((t (:foreground "#283a67"))))
 '(font-lock-variable-name-face ((t (:foreground "#9ea7a6"))))
 '(font-lock-warning-face ((t (:foreground "#f43841"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#96a6c8"))))
 '(link-visited ((t (:underline (:color foreground-color :style line) :foreground "#9e95c7"))))
 '(fringe ((t (:foreground "#453d41" :background "#101010"))))
 '(header-line ((t (:box nil :foreground "grey90" :background "grey20" :inherit (mode-line)))))
 '(tooltip ((t (:foreground "#ffffff" :background "#52494e"))))
 '(mode-line ((t (:foreground "blue" :background "gray"))))
 '(mode-line-buffer-id ((t (:foreground "red" :background "gray"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:foreground "#95a99f" :background "#282828"))))
 '(isearch ((t (:foreground "#000000" :background "#f5f5f5"))))
 '(isearch-fail ((t (:foreground "#000000" :background "#f43841"))))
 '(lazy-highlight ((((class color) (min-colors 88) (background light)) (:background "paleturquoise")) (((class color) (min-colors 88) (background dark)) (:background "paleturquoise4")) (((class color) (min-colors 16)) (:background "turquoise3")) (((class color) (min-colors 8)) (:background "turquoise3")) (t (:underline (:color foreground-color :style line)))))
 '(match ((t (:background "#52494e"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'pleroma)
